[package]
name = "compiler-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psl = { path = "../psl" }
schema-ast = { path = "../schema-ast" }
bincode = "1.3.1"
serde.workspace = true
clap = { version = "4.4.18", features = ["derive"] }
