[package]
name = "schema-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }

pest = "2.7.10"
pest_derive = "2.7.10"
serde.workspace = true
serde_json.workspace = true
