[package]
name = "parser-database"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
schema-ast = { path = "../schema-ast" }

indexmap.workspace = true
either = "1.6.1"
enumflags2 = "0.7"
rustc-hash = "1.1.0"
