[package]
name = "parser-database"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
schema-ast = { path = "../schema-ast" }
serde.workspace = true
either = { version = "1.6.1", features = ["serde"] }
indexmap.workspace = true
enumflags2.workspace = true
rustc-hash = "1.1.0"
