# Common types

[enumShapes.DatasourceParam]
description = """
The path to a live database taken as input. For flexibility, this can be the whole Prisma schemas as strings, or only the
connection string. See variants.
"""

[enumShapes.DatasourceParam.variants.SchemaString]
shape = "SchemaContainer"
isList = true

[enumShapes.DatasourceParam.variants.ConnectionString]
shape = "UrlContainer"
