[methods.dbExecute]
description = """
Execute a database script directly on the specified live database.\n\nNote that this may not be
defined on all connectors.
"""
requestShape = "DbExecuteParams"
responseShape = "DbExecuteResult"

[recordShapes.SchemaContainer]
description = "An object describing a Prisma schema and its file location."
fields.schema.shape = "string"
# Note: the name of the struct would suggest that `schema` models the contents of the Prisma schema file, rather than its path.
# This is counterintuitive.
fields.schema.description = "The contents of the Prisma schema file."

fields.file_path.shape = "string"
fields.file_path.description = "The file name of the Prisma schema file."

[recordShapes.UrlContainer]
description = "An object with a `url` field."
fields.url.shape = "string"

[recordShapes.DbExecuteParams]
description = "The type of params accepted by dbExecute."
fields.datasourceType.description = "The location of the live database to connect to."
fields.datasourceType.shape = "DbExecuteDatasourceType"
fields.script.description = "The input script."
fields.script.shape = "string"

[recordShapes.DbExecuteResult]
description = "The type of results returned by dbExecute."

[enumShapes.DbExecuteDatasourceType]
description = "The location of the live database to connect to."
variants.schema.description = "Prisma schema file and content to take the datasource URL from."
variants.schema.shape = "SchemaContainer"
variants.schema.isList = true

variants.url.description = "The URL of the database to run the command on."
variants.url.shape = "UrlContainer"
