[methods.introspect]
description = "Introspect the database (db pull)"
requestShape = "introspectParams"
responseShape = "introspectResult"

[recordShapes.introspectParams]
description = "Params type for the introspect method."

[recordShapes.introspectParams.fields.schemas]
shape = "introspectionDatamodel"
isList = true

[recordShapes.introspectParams.fields.force]
shape = "bool"

[recordShapes.introspectParams.fields.compositeTypeDepth]
shape = "isize"

[recordShapes.introspectParams.fields.namespaces]
shape = "string"
isList = true
isNullable = true

[recordShapes.introspectResult]
description = "Result type for the introspect method."

[recordShapes.introspectResult.fields.datamodels]
shape = "introspectionDatamodel"
isList = true

[recordShapes.introspectResult.fields.warnings]
shape = "string"
isNullable = true

[recordShapes.introspectResult.fields.views]
shape = "introspectionView"
isNullable = true
isList = true

[recordShapes.introspectionView]

[recordShapes.introspectionView.fields.schema]
shape = "string"

[recordShapes.introspectionView.fields.name]
shape = "string"

[recordShapes.introspectionView.fields.definition]
shape = "string"

[recordShapes.introspectionDatamodel]
description = "Datamodel introspection result with their file names."

[recordShapes.introspectionDatamodel.fields.fileName]
shape = "string"

[recordShapes.introspectionDatamodel.fields.content]
shape = "string"